### ISSUE TITLE
enqueue jobs in non-asyncio way

### ISSUE THREAD

**Issue by trim21** [janbjorge/pgqueuer#154]
Thanks for your work.

I understand, pgqueuer is designed for asyncio, and I try to use it in my thread based program. Is there anyway I can enqueue jobs without asyncio?

This is normally not a problem in single thread program, I can start a coroutine in main thread and use `loop.run_until_complete(...)`, but in multiple threading problem, this become a issue because eventloop may not be running in main thread, and `asyncio.run_coroutine_threadsafe(...).result()` will hang forever.

Can I get some help how to solve this?

**Comment by trim21** [comment]
OK, this can be done by execute sql command directly, `insert into pgqueuer (priority, created, updated, heartbeat, status, entrypoint, payload) ...`.

There is nothing else need do job for enqueueing a job.

**Comment by janbjorge** [comment]
That is correct, enqueue is just an insert. What framework are you using todo inserts? psycopg?

**Comment by trim21** [comment]
> That is correct, enqueue is just an insert. What framework are you using todo inserts? psycopg?


ys
