### ISSUE TITLE
document not correct for `qm.alive`

### ISSUE THREAD

**Issue by trim21** [janbjorge/pgqueuer#167]
```python
    # Ensures a clean and graceful shutdown of the job processing system.
    def handle_signal(*_args) -> None:
        qm.alive = False
```

and mypy:

```text
q\worker.py:230: error: Incompatible types in assignment (expression has type "bool", variable has type "Event")  [assignment]
```

should it be `qm.alive.set()`? and why set `alive` event to mark `QueueManager` as "dead"?

**Comment by janbjorge** [comment]
Docs are out of sync with the code, i will update. 

Unsure what you mean by 'why set alive event to mark QueueManager as "dead"?'.

**Comment by trim21** [comment]
> Unsure what you mean by 'why set alive event to mark QueueManager as "dead"?'.

I think it make more sence for `qm.exit.set()` or `qm.shutdown.set()` instead of `qm.alive.set()`

**Comment by janbjorge** [comment]
Yeah, that would make more sense. In early versions this was a boolean, where it made sense to call it alive. But at some point i needed it be awaitable. A would be happy to rename it to shutdown / exit.

**Comment by janbjorge** [comment]
@trim21 Could you take a look at https://github.com/janbjorge/pgqueuer/pull/168 ? What do you think?

**Comment by trim21** [comment]
I would suggest a new `def shutdown(self) -> None` method to set Event internally, and in case we have more think to handle in the future.
