### ISSUE TITLE
worker should not pick more job than `concurrency_limit`

### ISSUE THREAD

**Issue by trim21** [janbjorge/pgqueuer#173]
If long running job with `concurrency_limit=1` and `batch_size=3`, then worker may pick 3 jobs once, and 2 jobs just waiting in worker's own queue instead of global queueu (database).

This doesn't work well with multiprocessing based concurrency.

**Comment by janbjorge** [comment]
Thanks for bringing this up!

This behavior is a [known](https://pgqueuer.readthedocs.io/en/stable/limits.html#id1) implementation simplification. When batch_size > concurrency_limit, excess jobs are held by the worker's queue rather than being available globally, which can indeed limit multiprocessing efficiency. This was a trade-off to keep the initial implementation simple.

We're open to improvements, and if you'd like to work on enhancing this behavior—such as allowing unprocessed jobs to be re-queued globally—PRs are very much welcome!

**Comment by trim21** [comment]
I find if I set `batch_size=1` it will make per-worker pick job only `dequeue_timeout` is reached. To make it work in both case I need to do somethink like this `.run(batch_size=1, dequeue_timeout=timedelta(seconds=1))` ...

**Comment by trim21** [comment]
It's not a normal case with worker running and new job queued, but previous queued jobs with worker restarted. for example, run producer example before consumer example with batch size and concurrency_limit

**Comment by janbjorge** [comment]
What ive done so far is.

Enqueued by `uv run examples/producer.py 100`.

Changed the consumer to have `concurrency_limit=1`, and run the consumer as: `uv run python3 -m pgqueuer run examples.consumer.main --batch-size 1`. 

From what i can tell, its seems to work as expected?

**Comment by trim21** [comment]
Sorry, I can't reproduce this now.

**Comment by trim21** [comment]
OK, my bad. this looks like another issue, not what I descibed. this need at least 3 entry_point to reproduce this. and it's not 100% heppen in every run.

You can see it will pick only at most 2 jobs or even 1 by 1

(it pick job from up to down and rolling)
![image](https://github.com/user-attachments/assets/18ac03a3-9680-406a-8751-00933fe43fd7)

```python
import asyncio
from datetime import datetime, timedelta

import asyncpg
import psycopg
from pgqueuer.db import AsyncpgDriver
from pgqueuer.models import Job
from pgqueuer.qm import QueueManager
from pgqueuer.queries import Queries


pg_dsn = "postgres://postgres:postgres@192.168.2.18:5432/postgres"


async def producer() -> None:
    connection = await asyncpg.connect(pg_dsn)
    driver = AsyncpgDriver(connection)
    queries = Queries(driver)
    for i in range(100):
        for j in range(1, 10):
            await queries.enqueue(f"fetch_{j}", str(i).encode())

    for i in range(100):
        await queries.enqueue("fetch_0", str(i).encode())


async def consumer():
    connection = await asyncpg.connect(pg_dsn)
    driver = AsyncpgDriver(connection)
    qm = QueueManager(driver)

    for i in range(1, 10):

        @qm.entrypoint(f"fetch_{i}", retry_timer=timedelta(minutes=2), concurrency_limit=1)
        async def process_message(job: Job) -> None:
            await asyncio.sleep(3)

    @qm.entrypoint("fetch_0", retry_timer=timedelta(minutes=3), concurrency_limit=1)
    async def fetch2(job: Job) -> None:
        print("fetch_0 start", job.payload.decode(), datetime.now().astimezone())
        await asyncio.sleep(10)

    print("startup", datetime.now().astimezone())
    await qm.run(batch_size=1, dequeue_timeout=timedelta(minutes=1))


if __name__ == "__main__":
    with psycopg.connect(pg_dsn) as conn:
        conn.execute("delete from pgqueuer where entrypoint ~ '^fetch.*'")

    asyncio.run(producer())
    asyncio.run(consumer())
```

**Comment by janbjorge** [comment]
When i run the below query while running the code provided above there is a ish round robin of the entrypoints. 

If the implementation was correct, it should  1 picked for all of the entrypoints?

```sql
select count(*), status, entrypoint from pgqueuer group by (status, entrypoint) order by entrypoint, status;
 count | status | entrypoint 
-------+--------+------------
   100 | queued | fetch_0
    97 | queued | fetch_1
    97 | queued | fetch_2
    97 | queued | fetch_3
    97 | queued | fetch_4
    97 | queued | fetch_5
    97 | queued | fetch_6
    97 | queued | fetch_7
     1 | picked | fetch_7
    98 | queued | fetch_8
    98 | queued | fetch_9
(11 rows)
```

**Comment by trim21** [comment]
> When i run the below query while running the code provided above there is a ish round robin of the entrypoints.
> 
> If the implementation was correct, it should 1 picked for all of the entrypoints?
> 
> ```sql
> select count(*), status, entrypoint from pgqueuer group by (status, entrypoint) order by entrypoint, status;
>  count | status | entrypoint 
> -------+--------+------------
>    100 | queued | fetch_0
>     97 | queued | fetch_1
>     97 | queued | fetch_2
>     97 | queued | fetch_3
>     97 | queued | fetch_4
>     97 | queued | fetch_5
>     97 | queued | fetch_6
>     97 | queued | fetch_7
>      1 | picked | fetch_7
>     98 | queued | fetch_8
>     98 | queued | fetch_9
> (11 rows)
> ```

yes, it should 1 picked for all of the entrypoints. and this is also the behavoir also after worker running for some time.

**Comment by trim21** [comment]
maybe we should create each asyncio task to do picking/executing for each entry point?

**Comment by janbjorge** [comment]
I think that would work as a workaround?

**Comment by janbjorge** [comment]
If you could test that, it would be great. I think it should work, but not 100 sure.

**Comment by janbjorge** [comment]
@trim21 Locally https://github.com/janbjorge/pgqueuer/pull/174 seems to work, could give it a try?

**Comment by trim21** [comment]
> @trim21 Locally #174 seems to work, could give it a try?

not quiet sure, it may pick more jobs than batch_size or concurrency_limit

![image](https://github.com/user-attachments/assets/3d1b51a7-c9ec-41d1-8949-bd207e85b5b6)

**Comment by janbjorge** [comment]
@trim21 This got a bit more complex then i was hoping for, needed #175 as well. The test now passes. So will merge, and from what i can the issue is resolved. Please re-open if you find its not working expected. Note you will need to run the `upgrade` script first.

**Comment by trim21** [comment]
is manager id necessary? I thought a manager should already be able to track how many job it's picking. 🤔
