### ISSUE TITLE
[feature request] Named pipes

### ISSUE THREAD

**Issue by tobwen** [janbjorge/PgQueuer#18]
### Feature request
I don't know if the priority is just moving a job up or if it is also a type of “named pipe” as used in BeanstalkD. With BeanstalkD, for example, you can have a pipe “mail” for sending mails and a pipe "rendering" to do some rendering jobs.

You could of course implement this at payload level, but then it won't appear in the dashboard.

**Comment by janbjorge** [comment]
Thank you for your feature request and the explanation. Your suggestion about implementing a feature similar to BeanstalkD's "named pipes" for different types of jobs is insightful. However, as of now, I don't plan to build this feature into PgQueuer. I appreciate your understanding and encourage you to continue sharing any other ideas or feedback you may have.
