### ISSUE TITLE
Install in specific schema 

### ISSUE THREAD

**Issue by washigeri** [janbjorge/pgqueuer#241]
Hello 
I would like to use this package while having the tables in a specific schema which will be created beforehand.

I've already read issue #130, but it seems that no solution was found.

Also, it seems that I can't use the `--prefix` flag because it doesn't allow for dots in its value.

**Comment by janbjorge** [comment]
Hi,

For now, i think you have to set the schema via the dsn. I will add an option later today so it can be set via the cli tool, make sure your also set the correct `search_path` on any consumer/producer connections.

DSN ex. with schema.
```bash
 pgq install --pg-dsn 'postgresql://<user>:<password>@<hostname or ip>:5432/<database>?options=-c%20search_path=<your schema>'
```

**Comment by washigeri** [comment]
Thank you, I will try this and keep you updated!
