### ISSUE TITLE
`Driver` protocol should implement PEP 249

### ISSUE THREAD

**Issue by pdmtt** [janbjorge/pgqueuer#245]
Hello there!

First of all, I'd like to thank you for the amazing work you've been doing here!

I'm experimenting using this package with [`psycopg`](https://www.psycopg.org/psycopg3/docs/index.html) and found an issue when executing the consumer. See its code below, which is similar to the example provided:
```python
from psycopg import AsyncConnection
from pgqueuer import PgQueuer, AsyncpgDriver, Job


async def consume() -> PgQueuer:
    pgq = PgQueuer(
        AsyncpgDriver(
            await AsyncConnection.connect(...)        
        )
    )

    @pgq.entrypoint('entrypoint')
    async def _entrypoint(job: Job) -> None:
        if job.payload is None:
            return

        await process(job.payload.decode())

    return pgq
```
I executed this code the following way:
```bash
$ pgq run module.consume

Traceback (most recent call last):
  File ".../python3.12/site-packages/pgqueuer/sm.py", line 138, in run
    if not (await self.queries.has_table(self.queries.qbe.settings.schedules_table)):
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/pgqueuer/queries.py", line 126, in has_table
    rows = await self.driver.fetch(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.12/site-packages/pgqueuer/db.py", line 174, in fetch
    return [dict(x) for x in await self._connection.fetch(query, *args)]
                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AsyncConnection' object has no attribute 'fetch'
```

I believe `pgqueuer` shouldn't expect the driver to have a `fetch` method, because [PEP 249](https://peps.python.org/pep-0249) (Python Database API Specification v2.0) doesn't specify one.

I checked the documentation of `psycopg`, `asyncpg`, `sqlite3`, and it seems only `asyncpg` implements a `fetch` method.

Cheers!

**Comment by janbjorge** [comment]
Thanks for sharing your feedback and detailed example!

The intent behind the driver abstraction is to normalize database connections from pgqueuer’s perspective, ensuring it can interact seamlessly regardless of the underlying library. For instance, the PsycopgDriver wraps psycopg’s functionality into the expected interface (fetch, execute, etc.).

The code you provided looks great, and from my tests, it should work as intended. Could you confirm which version of psycopg and pgqueuer you’re using?

**Comment by washigeri** [comment]
@pdmtt 
Aren't you supposed to use the `PsycopgDriver` class since you're using `psycopg` instead of the `AsyncpgDriver`?

**Comment by pdmtt** [comment]
Hey, thanks for the reply.

I failed to notice that `AsyncpgDriver` was not a wrapper for all async postgres DBAPIs. The error was gone after changing to `PsycopgDriver`. My bad!

FYI, `psycopg.AsyncConnection.connect(...)` returns a connection with autocommit off by default. This caused an `AssertionError` at `pgqueuer.db.py:362`: 
```python
assert self._connection.autocommit
```
It was an easy fix after a quick code inspection, but it isn't mentioned in the documentation that autocommit is needed.

If you use an `psycopg.AsyncConnection` with the default configuration (autocommit off) to enqueue tasks, they won't be commited by `pgqueuer`. This is worse than before because this problem is quiet, which makes debugging harder.

Since that's not the scope of this issue, I'm closing it. 
Thanks again.

**Comment by janbjorge** [comment]
@pdmtt Thanks the feedback, i will improve the exception message as well as update the docs. to mention that the connections must be in 'autocommit mode'.
