### ISSUE TITLE
Schedule for specific time

### ISSUE THREAD

**Issue by agenore** [janbjorge/pgqueuer#246]
Would it be easy to schedule a task for a specific time to run once?

I feel it would make pgqueuer close to feature complete

**Comment by janbjorge** [comment]
Hi, there is an execute after option to the queue function i provide. Would that suit your need? 

https://github.com/janbjorge/pgqueuer/blob/b71de968eccb3bec2c2337b86e2ca301d1091b3a/pgqueuer/queries.py#L193-L245

The docs. might need a bit of love in this topic, but typically it will execute after the datetime, but in worst case is approx. the after-timestamp + dequeue-timeout
